project:
  type: book
  output-dir: _book

book:
  title: "md in qmd"
  date: "12/20/2024"
  description: Testing
  author:
    - name: Mikkel Roald-Arbøl
  chapters:
    - index.qmd

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt
